### ISSUE TITLE
`origin_type_checkers` not exported from typeguard

### ISSUE THREAD

**Issue by caneff** [nanne-aben/strictly_typed_pandas#102]
How is [this](https://github.com/nanne-aben/strictly_typed_pandas/blob/main/strictly_typed_pandas/typeguard.py#L68) even working? AFAICT typeguard doesn't export origin_type_checkers anywhere, so how is it that we have access to it here?

**Comment by caneff** [comment]
Apologies I was looking at something wrong. Please ignore.

**Comment by nanne-aben** [comment]
No problem!
