### ISSUE TITLE
Handle the error message better when an IndexedDataSet is given a data frame without an index

### ISSUE THREAD

**Issue by caneff** [nanne-aben/strictly_typed_pandas#110]
Currently the following 

```python
import pandas as pd
import strictly_typed_pandas as stp
class Ind:
  a: str

class cols:
  b: str

IndexedDf = stp.IndexedDataSet[a, b]

df = pd.DataFrame({"a":["a1","a2"], "b":["b1","b2"]})
df.pipe(IndexedDf)
```
fails with the message

`TypeError: Data contains the following columns not present in schema: {None}`

This confused me when I had forgotten to set the index.  We should add a check to see if something that is expected to have  an index is missing it, and if so give an error more like `Data expected to have a named index, but the index has no names (Did you remember to add the columns to the index?)`

**Comment by nanne-aben** [comment]
Hi @caneff ! I agree, looks like a great idea! Would you like to implement it?
