### ISSUE TITLE
feat: poetry build

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nanne-aben/strictly_typed_pandas#140]

**Comment by nanne-aben** [comment]
Hi @dzmitry-lahoda , thanks for opening an issue! Can you elaborate a bit?

**Comment by dzmitry-lahoda** [comment]
make this package to be poetry package, so can so poetry add, install.

**Comment by nanne-aben** [comment]
The package is already pip installable through pypi. Does that not allow you to install it through poetry?

**Comment by dzmitry-lahoda** [comment]
I do not use pypi. I build from scratch all things.

**Comment by nanne-aben** [comment]
That seems like a really specific usecase, probably unique to you. I don't think that warrants us moving from setuptools to poetry.

Or are there other benefits of moving to poetry that I'm not seeing here?

Mind if I ask you why you want to build everything from scratch btw?

**Comment by dzmitry-lahoda** [comment]
Poetry is like Cargo. Cargo is cool.
Poetry has best reproduce ability and repeat ability in python ecosystem, and yet flexible. These all people want. Poetry repacing setuptools, setuptools is legacy.
So Nix likes Poetry, and I like Nix. So all Poetry packages are very good for Nix. Nix builds from scratch.

**Comment by dzmitry-lahoda** [comment]
Oh, Python gets Rusted fast, I guess ypur saw it. Cargo is same as Poetry. And also with open system  like blockchain, the is nor trust, so only option to make dependency graph to the end traceable. Blockchain likes Rust. Any supply chain attack costs millions.

So, Poetry is future of Python.

**Comment by dzmitry-lahoda** [comment]
setuptools is dead tbh

**Comment by dzmitry-lahoda** [comment]
@nanne-aben  thank you.  so i use poetry because it is the best out of build options in python. it is reproducible determinstic with integration of project with virtual env shell. that is default in rust, haskell, go. python get it, hope python people will get it too:)
