### ISSUE TITLE
Documentation showing deprecation warnings for pandas

### ISSUE THREAD

**Issue by caneff** [nanne-aben/strictly_typed_pandas#161]
Looks like we have a deprecation warning leaking through ([here](https://strictly-typed-pandas.readthedocs.io/en/latest/getting_started.html) at least but I didn't check every page). So I think the right answer is to just suppress the warning (since we will want to support 2.x's requirements even when 3 is out). Agree?

**Comment by nanne-aben** [comment]
Thanks @caneff, good catch! I've added `pyarrow` to the `requirements-dev.txt`, that seems to have resolved it.
