### ISSUE TITLE
"No cloning" example doesn't act as documentation presumes it will

### ISSUE THREAD

**Issue by shippy** [nanne-aben/strictly_typed_pandas#84]
Please note that the output of `df2.name` is the initial value of `df1.name`, meaning that assignment to `df1.name` did not apparently change `df2.name`. So the whole warning about pointers doesn't seem to apply. This is currently [seen on ReadTheDocs](https://strictly-typed-pandas.readthedocs.io/en/latest/advanced.html#No-cloning):

> When a DataFrame is cast to a DataSet, the underlying data isn’t cloned (unless you use DataSet[Schema](..., copy=True)). This is great for memory purposes, but it does require some caution. For example, consider the following pandas script:
> 
> ```
> df1 = pd.DataFrame({"id": [1, 2, 3], "name": ["John", "Jane", "Jack"]})
> df2 = pd.DataFrame(df1)
> df1.name = [1, 2, 3]
> df2.name
> ```
> ```
> # Note: This output appears incorrect, or at least inconsistent with the text!
> 0    John
> 1    Jane
> 2    Jack
> Name: name, dtype: object
> ```
> Here, df1 and df2 essentially point to the same data, so changing one of them changes the other one too. This behaviour extends to DataSet as well.
> 
> ```
> class Schema:
>     id: int
>     name: str
> 
> df1 = pd.DataFrame({"id": [1, 2, 3], "name": ["John", "Jane", "Jack"]})
> df2 = DataSet[Schema](df1)
> df1.name = [1, 2, 3]
> df2.name
> ```
> ```
> 0    John
> 1    Jane
> 2    Jack
> Name: name, dtype: object
> ```

**Comment by nanne-aben** [comment]
Ah, good find! Thanks!

The documentation gets rebuild with each release. It must have been fixed in pandas over time and I hadn't noticed. For example, at this old version it's still showing the former behavior:
https://strictly-typed-pandas.readthedocs.io/en/v0.1.5/advanced.html

But in newer documentation it appears to be fixed. I'll remove that part of the documentation.
