### ISSUE TITLE
Handle None in schemas

### ISSUE THREAD

**Issue by doublethink13** [nanne-aben/strictly_typed_pandas#9]
I'm trying to run the following code:

```python
class TypeTest:
    a: str | None


ds = DataSet[TypeTest]([{"a": None}])
```

However, I'm getting the following error: `TypeError: Column a is of type numpy.object, but the schema suggests str | None`

How can I handle `None` type in the schema?

**Comment by nanne-aben** [comment]
No need to define it. A lot of pandas data types, strings included, can deal with None types off the bat. One notable exception is integers: by default, Pandas converts integers with missing values to floats, so if you don't want that, you'll have to use the more recent `pd.Int64Dtype` (which does allow for missing values).

```python
import pandas as pd

from strictly_typed_pandas import DataSet


class TypeTest:
    a: float
    b: str
    c: pd.Int64Dtype


DataSet[TypeTest](
    {
        "a": [1.0, None],
        "b": ["hi", None],
        "c": pd.Series([1, None], dtype=pd.Int64Dtype())
    }
)
```

**Comment by doublethink13** [comment]
Correct me if I'm wrong, but then and/or:

- My schema is lying, because `a`, `b` and `c` can be `None`
- My schema requires implicit knowledge of pandas/numpy

**Comment by nanne-aben** [comment]
I agree that pandas is pretty inconsistent right now when it comes to missing values. The way they put it themselves:

> The choice of using NaN internally to denote missing data was largely for simplicity and performance reasons. Starting from pandas 1.0, some optional data types start experimenting with a native NA scalar using a mask-based approach.

Source: https://pandas.pydata.org/docs/user_guide/missing_data.html

I hope that eventually they'll fully move to these new (currently experimental) data types. That would make the behaviour consistent across data types.

That would also mean that the default behaviour of every column would be that it can accept missing values. I think that's fine, no need to specifically annotate that.
