### ISSUE TITLE
Add black formatting?

### ISSUE THREAD

**Issue by caneff** [nanne-aben/strictly_typed_pandas#97]
I'm always a fan of having autoformatting as part of a package and precommit.  Would it be ok to add black here? I'd be happy to take it on.

**Comment by nanne-aben** [comment]
Yes, that would be a great addition! Can we set it up with `line-length=100`?

I also like isort and docformatter. I've set them up for another [package](https://github.com/kaiko-ai/typedspark) that I maintain, but I never got around setting them up here. If you like these and have time, would love to have them here too!

**Comment by caneff** [comment]
Will do

**Comment by caneff** [comment]
Fixed by #99 #101  and #103
